<h3>임의의 데이터를 만들어서, 다중회귀분석을 수행한다.</h3>
<ul>
    <li>학습 데이터를 벡터 형태로 만들어서 수행 </li>
    <li>학습 데이터를 행렬 형태로 만들어서 수행</li>
</ul>

<b>1. 학습 데이터를 벡터 형태로 만들어서 회귀분석 수행</b>

In [111]:
import tensorflow as tf

In [125]:
x1 = [1,0,3,0,6]
x2 = [0,2,0,4,5]
y = [1,2,3,4,5]

w1 = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
w2 = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b =tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [133]:
h = x1*w1 + x2*w2 + b
cost = tf.reduce_mean(tf.square(y-h))
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(1000):
        _, c_w1, c_w2, c_b, c_cost = sess.run([train, w1, w2 , b, cost])
        if step % 100 == 0:
            print(c_w1, c_w2, c_b, c_cost)
    print(sess.run(h))

[-0.41771838] [0.6499498] [-0.68128204] 22.357489
[0.3271547] [0.6574938] [0.53991777] 0.7132033
[0.27723676] [0.5643359] [1.0399736] 0.43546242
[0.25421953] [0.52206045] [1.2681831] 0.3776271
[0.24371573] [0.5027693] [1.3723223] 0.3655836
[0.23892255] [0.4939661] [1.4198438] 0.36307564
[0.23673524] [0.48994902] [1.4415296] 0.36255342
[0.23573713] [0.48811585] [1.4514253] 0.36244476
[0.23528162] [0.48727927] [1.4559413] 0.36242205
[0.23507372] [0.48689747] [1.4580026] 0.3624173
[0.2349789] [0.4867234] [1.4589424] 0.36241633
[0.23493561] [0.4866439] [1.4593716] 0.36241615
[0.23491594] [0.4866076] [1.4595672] 0.3624161
[0.23490694] [0.48659116] [1.4596561] 0.36241603
[0.23490283] [0.48658362] [1.4596968] 0.36241606
[0.23490106] [0.48658025] [1.4597147] 0.36241612
[0.23490012] [0.48657858] [1.459724] 0.36241603
[0.23490012] [0.48657858] [1.459724] 0.36241603
[0.23490012] [0.48657858] [1.459724] 0.36241603
[0.23490012] [0.48657858] [1.459724] 0.36241603
[0.23490012] [0.48657858] [1.459724]

In [176]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [179]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]))
w2 = tf.Variable(tf.random_normal([1]))
w3 = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

h = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(h-y))
optimizer = tf.train.GradientDescentOptimizer(0.00002)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(100):
        _, c_w1, c_w2, c_w3, c_b, c_cost, c_h = sess.run([train, w1, w2 , w3, b, cost, h],
                                              feed_dict ={x1:x1_data, x2:x2_data, x3:x3_data, y:y_data})
        if step % 10000 == 0:
            print(c_w1, c_w2, c_w3, c_b, c_cost)
            
    print(sess.run(h, feed_dict={x1:x1_data, x2:x2_data, x3:x3_data}))

[0.29375377] [2.4493926] [-0.70867395] [1.3545458] 298.80298
[163.37532 176.75848 184.49785 196.5037  133.87807]


<b>2. 위에서 실습한 데이터를 행렬로 바꾸어 실행해본다.</b>

In [181]:
import numpy as np

In [189]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [191]:
x_data = np.array([np.array(x1_data), np.array(x2_data), np.array(x3_data)])
x_data = x_data.T

In [196]:
x_data

array([[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.]])

In [199]:
y_data = np.array(y_data).reshape(5,1)

In [208]:
y_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]])

In [224]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([3,1]))
b = tf.Variable(tf.random_normal([1]))

h = tf.matmul(x, w) + b

cost  = tf.reduce_mean(tf.square(h-y))
optimizer = tf.train.GradientDescentOptimizer(0.00002)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10000):        
        _, cur_w, cur_cost = sess.run([train, w, cost], feed_dict = {x:x_data, y:y_data})
        
        if step % 1000 ==0:
            print("w: \n", cur_w,"\n cost:",  cur_cost)
            print()
            
    print(sess.run(h, feed_dict={x:x_data}))

w: 
 [[0.17636466]
 [0.66730636]
 [0.82277095]] 
 cost: 58128.54

w: 
 [[0.4577269 ]
 [0.59779805]
 [0.94754547]] 
 cost: 2.2963717

w: 
 [[0.5629236 ]
 [0.49567062]
 [0.94436175]] 
 cost: 1.1942961

w: 
 [[0.63045   ]
 [0.43944928]
 [0.93308705]] 
 cost: 0.79241383

w: 
 [[0.67576903]
 [0.40977326]
 [0.9175537 ]] 
 cost: 0.6300212

w: 
 [[0.7078855 ]
 [0.39539158]
 [0.89997035]] 
 cost: 0.55108184

w: 
 [[0.7320509]
 [0.3897681]
 [0.8815997]] 
 cost: 0.50259525

w: 
 [[0.75133216]
 [0.38910708]
 [0.8631585 ]] 
 cost: 0.46641025

w: 
 [[0.7675238 ]
 [0.39120886]
 [0.8450445 ]] 
 cost: 0.43621618

w: 
 [[0.78168315]
 [0.39479873]
 [0.82747126]] 
 cost: 0.40970725

[[151.1333 ]
 [184.805  ]
 [180.39304]
 [196.85359]
 [141.49255]]


<b>3. 새로운 데이터로 동일하게 회귀분석을 실행 ( 행렬의 차원은 동일 ) </b>

In [235]:
exam_data = np.array([73,80,75,152,
                    93,88,93,185,
                    89,91,90,180,
                    96,98,100,196,
                    73,66,70,142,
                    53,46,55,101]).reshape(6,4)

In [246]:
y_data = exam_data[:,3].reshape(6,1)

In [247]:
y_data

array([[152],
       [185],
       [180],
       [196],
       [142],
       [101]])

In [251]:
x_data = exam_data[0:6,0:3]

In [252]:
x_data

array([[ 73,  80,  75],
       [ 93,  88,  93],
       [ 89,  91,  90],
       [ 96,  98, 100],
       [ 73,  66,  70],
       [ 53,  46,  55]])

In [253]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([3,1]))
b = tf.Variable(tf.random_normal([1]))

h = tf.matmul(x, w) + b

cost  = tf.reduce_mean(tf.square(h-y))
optimizer = tf.train.GradientDescentOptimizer(0.00002)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10000):        
        _, cur_w, cur_cost = sess.run([train, w, cost], feed_dict = {x:x_data, y:y_data})
        
        if step % 1000 ==0:
            print("w: \n", cur_w,"\n cost:",  cur_cost)
            print()
            
    print(sess.run(h, feed_dict={x:x_data}))

w: 
 [[ 1.5550978 ]
 [ 0.62892985]
 [-0.34119108]] 
 cost: 4493.6543

w: 
 [[ 1.5655798 ]
 [ 0.7257992 ]
 [-0.27131298]] 
 cost: 1.0227212

w: 
 [[ 1.5317616 ]
 [ 0.7438245 ]
 [-0.25549796]] 
 cost: 0.934419

w: 
 [[ 1.5061113 ]
 [ 0.75142   ]
 [-0.23755866]] 
 cost: 0.8813465

w: 
 [[ 1.4852704 ]
 [ 0.7537723 ]
 [-0.21924524]] 
 cost: 0.84170705

w: 
 [[ 1.4674643 ]
 [ 0.7535395 ]
 [-0.20140247]] 
 cost: 0.80915624

w: 
 [[ 1.4517423 ]
 [ 0.75208104]
 [-0.18441886]] 
 cost: 0.7815404

w: 
 [[ 1.4375753 ]
 [ 0.7500875 ]
 [-0.16844761]] 
 cost: 0.75782675

w: 
 [[ 1.4246566 ]
 [ 0.7479077 ]
 [-0.15352616]] 
 cost: 0.73740906

w: 
 [[ 1.4127954 ]
 [ 0.745714  ]
 [-0.13963456]] 
 cost: 0.7197535

[[152.37563 ]
 [184.08052 ]
 [181.08401 ]
 [194.83488 ]
 [142.59903 ]
 [101.590805]]
