In [1]:
import tensorflow as tf

C:\Users\kitcoop\Anaconda3\envs\test\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
from tensorflow.examples.tutorials.mnist import input_data

In [3]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
print(mnist.test.images)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
print(mnist.test.labels[0])

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [5]:
print(mnist.test.images[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [6]:
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

w = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

h = tf.nn.softmax(tf.matmul(x, w + b))
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y * tf.log(h), axis=1))
#train = tf.train.GradientDescentOptimizer(0.002).minimize(cross_entropy)
train = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

In [7]:
with tf.Session() as sess : 
    sess.run(tf.global_variables_initializer())
    for step in range(10000):
        batch_xs, batch_ys = mnist.train.next_batch(100)
        _, cur_cost = sess.run([train, cross_entropy], feed_dict = {x:batch_xs, y:batch_ys})
        #print(cur_cost)
        if(step % 1000 == 0):
            print(cur_cost)
    corr_pred = tf.equal(tf.argmax(h, 1), tf.argmax(y, 1))
    accuracy = tf.reduce_mean(tf.cast(corr_pred, "float"))
    
    print(sess.run(accuracy, feed_dict={x:mnist.test.images, y:mnist.test.labels}))
    
    saver = tf.train.Saver()
    savefile = saver.save(sess, "modelsave/mnist_softmax.ckpt")

2.3025854
0.36250675
0.3463309
0.26658878
0.2749347
0.14567934
0.15010501
0.48720452
0.48707286
0.2711896
0.9259
