<h3>퍼셉트론 분류: 텐서 플로우</h3>

In [2]:
import tensorflow as tf
import numpy as np

C:\Users\kitcoop\Anaconda3\envs\test\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

In [6]:
len(x_data), len(y_data)

(6, 6)

In [33]:
x = tf.placeholder(tf.float32, shape=[None, 2])
y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
h = tf.sigmoid(tf.matmul(x,w)+ b)

cost = -tf.reduce_mean(y * tf.log(h) + (1-y)*tf.log(1-h))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

predict = tf.cast(h > 0.5 , dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict, y), dtype=tf.float32))

In [40]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for s in range(100001):
        _, cur_c, cur_w = sess.run([train, cost, w], feed_dict={x: x_data, y:y_data})
        
        if s % 10000 == 0:
            print(cur_c)
    
    hy, pr, ac = sess.run([h, predict, accuracy], feed_dict = {x:x_data, y:y_data})
    print(hy, pr, ac)

0.7727594
0.1352914
0.08092915
0.058073755
0.04541867
0.037348885
0.031740803
0.027611332
0.024440786
0.021927657
0.019886399
[[2.7827840e-04]
 [3.1685118e-02]
 [3.9076108e-02]
 [9.5610392e-01]
 [9.9822360e-01]
 [9.9968588e-01]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 1.0


<b>새로운 값으로 분류
   

In [43]:
x_data_new = [[1,1], [3,3,], [4,4]]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    print(sess.run(predict, feed_dict={x:x_data_new}))
    print(sess.run(w))

[[1.]
 [1.]
 [1.]]
[[ 0.89417094]
 [-0.7001453 ]]
