<b>Softmax 수식 연습</b>

In [56]:
import numpy as np

In [81]:
def softfunc(x):
    x_max = np.max(x, axis=1).reshape(len(x),1)
    x = x - x_max
    return np.exp(x)/np.sum(np.exp(x), axis=1).reshape(len(x),1)

In [58]:
data = np.array([[0.3, 2.9, 4.0],[1000,1001,1002]])

In [60]:
softfunc(data)

array([[0.01821127, 0.24519181, 0.73659691],
       [0.09003057, 0.24472847, 0.66524096]])

<b>tensorflow softmax 함수 활용</b>

In [196]:
xdata = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],
         [1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
# ydata = [[2],[2],[2],[1],[1],[1],[0],[0]]

ydata = [[0,0,1],[0,0,1],[0,0,1],  # 2를 [0,0,1]표현함 
         [0,1,0],[0,1,0],[0,1,0],  # 1을 [0,1,0]으로표현
         [1,0,0],[1,0,0]  # 0을 [0,1,0]으로표현       
        ]

In [197]:
np.array(ydata).shape

(8, 3)

In [198]:
np.array(xdata).shape

(8, 4)

In [199]:
print(np.sum(softfunc(xdata) , axis=1))
softfunc(xdata)

[1. 1. 1. 1. 1. 1. 1. 1.]


array([[0.1748777 , 0.47536689, 0.1748777 , 0.1748777 ],
       [0.19661193, 0.07232949, 0.53444665, 0.19661193],
       [0.20603191, 0.02788339, 0.20603191, 0.56005279],
       [0.15416989, 0.00767567, 0.41907722, 0.41907722],
       [0.00194695, 0.78545382, 0.10629962, 0.10629962],
       [0.00483724, 0.01314897, 0.26410418, 0.71790961],
       [0.00224095, 0.33258635, 0.33258635, 0.33258635],
       [0.00082557, 0.33305814, 0.33305814, 0.33305814]])

In [200]:
len(xdata)

8

In [201]:
np.max(xdata , axis=1).reshape(len(xdata),1)

array([[2],
       [3],
       [4],
       [5],
       [7],
       [6],
       [6],
       [7]])

In [202]:
import tensorflow as tf

In [204]:
t_x = np.array([[0,1,0]])
t_y = np.array([0.2,0.7,0.1])

In [205]:
np.sum(t_x*np.log(t_y), axis =1 )

array([-0.35667494])

In [206]:
xdata

[[1, 2, 1, 1],
 [2, 1, 3, 2],
 [3, 1, 3, 4],
 [4, 1, 5, 5],
 [1, 7, 5, 5],
 [1, 2, 5, 6],
 [1, 6, 6, 6],
 [1, 7, 7, 7]]

In [207]:
x = tf.placeholder(tf.float32, [None, 4])
y = tf.placeholder(tf.float32, [None, 3])
w = tf.Variable(tf.random_normal([4,3]))
b = tf.Variable(tf.random_normal([3]))

#model = softfunc(tf.matmul(x,w)+b)
model = tf.nn.softmax(tf.matmul(x,w)+b) # 
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(model), axis=1))

optimizer = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [208]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(10000):
        _, cur_cost= sess.run([optimizer, cost], feed_dict = {x:xdata , y:ydata})
        if step % 1000 == 0:
            print(cur_cost)
#             print(sess.run(model))

9.086694
0.22594538
0.14879459
0.110459566
0.08762412
0.07252
0.06181054
0.053831004
0.047660545
0.042749204
