<h1>Tensorflow basic</h1>
<ul>
    <li>1. Placeholder</li>
    <li>2. Variable</li>
    <li>3. Tensor Board</li>
</ul>

<h3>1. Placeholder 이해하기 </h3>

In [2]:
import numpy as np
import tensorflow as tf

C:\Users\kitcoop\Anaconda3\envs\test\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
ph = tf.placeholder(dtype=tf.float32, shape=[3,3])
y = tf.add(ph, 10.)

with tf.Session() as sess:
    tand_arr = np.random.rand(3,3)
    print(sess.run(y, feed_dict={ph:tand_arr}))

[[10.329745 10.921095 10.208966]
 [10.375683 10.791717 10.820864]
 [10.162183 10.719334 10.503665]]


In [8]:
v1 = 3; v2 = 4; v3 = 5;

In [10]:
ph1 = tf.placeholder(dtype=tf.int32)
ph2 = tf.placeholder(tf.int32)
ph3 = tf.placeholder(tf.int32)

print(ph1)
print(ph2)

Tensor("Placeholder_8:0", dtype=int32)
Tensor("Placeholder_9:0", dtype=int32)


In [12]:
result_value = ph1 + ph2 * ph3
with tf.Session() as sess:
    fdict = {ph1:v1, ph2:v2, ph3:v3}
    result = sess.run(result_value, feed_dict=fdict)
    print(result)

23


In [13]:
arr1 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = [1,2,3]

ph_arr1 = tf.placeholder(dtype=tf.float32)
ph_arr2 = tf.placeholder(dtype=tf.float32)
fdict = {ph_arr1:arr1, ph_arr2:arr2}
res = ph_arr1 * ph_arr2 

In [15]:
with tf.Session() as sess:
    result2 = sess.run(res, feed_dict = fdict)
    print(result2)

[[ 1.  4.  9.]
 [ 4. 10. 18.]
 [ 7. 16. 27.]]


In [19]:
a = tf.placeholder(dtype=tf.int32, shape=[None]) # 1차원 벡터 받겠다.(n개)
b = 10
c = a * 10

with tf.Session() as sess:
    rr = sess.run(c, feed_dict={a:[1,2,3,4,5]})

In [31]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)

sess = tf.Session()
print(sess.run([node1, node2]))
print(sess.run((node1, node2)))
sess.close()

[3.0, 4.0]
(3.0, 4.0)


In [35]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
ab_mul = tf.multiply(a,b)

sess = tf.Session()
print(sess.run(ab_mul, feed_dict={a:3, b:4}))
print(sess.run(ab_mul, feed_dict={a:[1,3], b:[2,4]}))

sess.close()

12.0
[ 2. 12.]


<h3>2. Variable 이해하기</h3>

In [40]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = tf.placeholder(tf.float32)
model = w * x + b

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

print(sess.run(model, {x:[1,2,3,4]}))
sess.close()

[0.         0.3        0.6        0.90000004]


In [61]:
# Variable 초기화 방법 1
x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')

sess = tf.Session()
f = x*x*y + 2
sess.run(tf.global_variables_initializer())
#print(sess.run(f))
print(f.eval(session=sess))
sess.close()

38


In [63]:
# Variable 초기화 방법 2
with tf.Session() as sess:
    x.initializer.run()
    y.initializer.run()
    print(f.eval())

38


<h3>3. TensorBoard</h3>

In [74]:
a = tf.add(10, 20, name="a_add")
b = tf.multiply(a, 5, name="b_mul")

c = tf.add(3,4, name="c_add")
d = tf.multiply(c, 5, name="d_mul")
e = tf.add(b, d , name = "e_add_result")

with tf.Session() as sess:
    print(sess.run(e))
    tf.summary.FileWriter("tensorboard/", sess.graph)

185
